package com.zowak.rasterrizer.viewform;




import com.zowak.rasterrizer.RasterImage;
import com.zowak.rasterrizer.grids.BasicGrid;
import com.zowak.rasterrizer.grids.EditGrid;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author christophnowak
 */
public class ViewScreen extends javax.swing.JFrame {

    /**
     * Creates new form ViewGrid
     */
    public ViewScreen() {
        initComponents();
        viewGrid.setRowMarkerVisible(true);
        viewGrid.setRasterType(BasicGrid.RASTER_PUNCTUAL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        viewGrid = new EditGrid();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Muster");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        scrollPane.setViewportView(viewGrid);

        viewGrid.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                viewGridMouseWheelMoved(evt);
            }
        });
        viewGrid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                viewGridKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout viewGridLayout = new javax.swing.GroupLayout(viewGrid);
        viewGrid.setLayout(viewGridLayout);
        viewGridLayout.setHorizontalGroup(
            viewGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        viewGridLayout.setVerticalGroup(
            viewGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        scrollPane.setViewportView(viewGrid);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewGridMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_viewGridMouseWheelMoved
        viewGrid.increaseRasterSize(evt.getWheelRotation());
        scrollPane.revalidate();
        
    }//GEN-LAST:event_viewGridMouseWheelMoved

    private void viewGridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_viewGridKeyPressed

    }//GEN-LAST:event_viewGridKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            viewGrid.nextRow();
        }else if(evt.getKeyCode() == KeyEvent.VK_UP){
            viewGrid.previousRow();
        }
    }//GEN-LAST:event_formKeyPressed

    public void setRasterImage(RasterImage rasterImage){
        viewGrid.setRasteredImage(rasterImage);
        scrollPane.revalidate();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private EditGrid viewGrid;
    // End of variables declaration//GEN-END:variables
}
